server:
  port: 8083

spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/bank_customers/**
            
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/bank_accounts/**
        
  config:
    import: optional:configserver:http://localhost:8888           
           
           
#eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka  
       
       
           