server:
  port: 8888
  
spring:
  application:
    name: CONFIG-SERVER   
    
   
  cloud:
    config:
      server:
        git:
          uri: https://github.com/san-369/microservices-config       # get the url of git repository and paste it here
          clone-on-start: true 



